# Generated by Django 5.2.4 on 2025-08-12 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_artist_alter_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_art',
            field=models.ImageField(blank=True, null=True, upload_to='song_images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='spotify.artist'),
        ),
    ]
