# Generated by Django 5.2.4 on 2025-08-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_remove_song_artist_delete_playlist_song_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artists',
        ),
    ]
