# Generated by Django 5.2.4 on 2025-08-13 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_artist_image_alter_song_album_art_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='album_images/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='spotify.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='albumss',
            field=models.ManyToManyField(blank=True, related_name='artists', to='spotify.album'),
        ),
    ]
