# Generated by Django 5.2.4 on 2025-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_rename_artist_song_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverimage', models.ImageField(blank=True, null=True, upload_to='albums/')),
            ],
        ),
    ]
