# Generated by Django 5.2.4 on 2025-08-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_album_artist_albumss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='albumss',
            new_name='albums',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumartist', to='spotify.artist'),
        ),
    ]
