# Generated by Django 5.2.4 on 2025-08-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_rename_albumss_artist_albums_alter_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='albums',
            new_name='albums_list',
        ),
    ]
