# Generated by Django 5.2.4 on 2025-08-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_rename_albums_artist_albums_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover_art',
            new_name='cover_image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='albums_list',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.artist'),
        ),
    ]
