# Generated by Django 5.2.4 on 2025-08-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_album_artist_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
