# Generated by Django 5.2.4 on 2025-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_rename_cover_art_album_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='spotify.artist'),
        ),
    ]
