# Generated by Django 5.2.4 on 2025-08-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_album_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='spotify.album'),
        ),
    ]
