# Generated by Django 5.2.4 on 2025-08-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_song_album_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
