# Generated by Django 5.2.4 on 2025-08-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_remove_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Songs',
            field=models.ManyToManyField(blank=True, related_name='albums', to='spotify.song'),
        ),
    ]
