# Generated by Django 5.2.4 on 2025-08-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_album_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Songs',
            new_name='songs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album_list',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='songs', to='spotify.artist'),
        ),
    ]
