# Generated by Django 5.2.4 on 2025-08-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0013_alter_album_artists_remove_song_artist_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='albums', to='spotify.artist'),
        ),
    ]
